# Generated by Django 5.0.4 on 2024-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Work title')),
                ('image', models.ImageField(upload_to='works')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='Langauge')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.TextField(verbose_name='About service')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='end_date',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='offer_status',
            new_name='programming_langauge',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='proj_report',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
    ]
